### ISSUE TITLE
Providing security to webhooks

### ISSUE THREAD

**Issue by akhil-naidu** [leewardslope/t2d-ui#62]
The webhooks I'm introducing allows t2d admins even to send some terminal commands via HTTP requests. It is one of the most convenient ways to control users server with great precision, but at the same time open up few security issues. Here I'm mentioning few issues and necessary solutions to be taken.

---

## Tasks

- [ ] Trigger Rule: Whitelisting IP's
- [ ] Trigger Rule: Add a random string => triggerString => Whick will act as token
- [ ] Unique URL prefix => ourDefinedString
- [ ] Generate triggerString and ourDefinedString during account creation
- [ ] Make the URLs dynamically generated
- [ ] Make the webhook run, command dynamically generated and a separate Playbook
- [ ] Checks and Verifications

---

## Issues

- The webhooks port is open to the public, making it potentially vulnerable to many attacks.
- The query strings might be visible to users, and they can decode and reconstruct our connection pattern for malicious purposes.

## Solutions

By introducing VPN, we can actually make negate it being a public port, but every other customer can also interact with the ports, so it doesn't solve the problem. The attacker can use our services to precisely target with more accuracy. Also, there is no pointing in making things more complicated.

So, I was thinking of introducing these restrictions => Every webhook will have a `trigger rule`, and I define these rules for every server. An example would be, whitelisting the IP addresses and adding some random token value for every user. We will send these trigger rules via Ansible during the server setup. Preferably, I will try to make at least one trigger rule with a unique pattern specified to an individual and will only use that trigger rule for most of the cases.

Alternatively, I would like to use dynamically configured URLs for different users to make decoding our URL pattern hard. This is an example of a webhook URL to listing users apps.

`t2d-${userId}.leewardslope.com/${ourDefinedString}/list?token=${triggerRule}`

Here, not just one but two random variables and one unique ID are being used. The reason is simple.
**${userID}** => It is easy for attackers to find such data, and we are also not making it visible in the URL itself
**${triggerRule}** => We are hardcoding this value into the user's server and storing it, so there might be a chance the user himself reveal such information
**${ourDefinedString}** => This is something completely at our discretion, and we will not be known to anyone, except for our dB.

---

With this kind of arrangement, every Safelisting server can easily access and also, we can trigger this without our server's interaction via frontend without worrying about security.

> In my opinion, this is more than sufficient for now.
